- camtrap-dp-profile.json
- observations-table-schema.json
Fixes #115 and #108 and #120. Was tested on an example data package.
~I would like to have an answer to #120 before finishing this PR.~
> Allow multiple vernacular names in metadata, remove from observations.csv

- camtrap-dp-profile.json
The specs require the property `url`, while it is actually called `path`
> Fix typo: url is called path

- camtrap-dp-profile.json
What bait was used is less important at project level and it can conflict with the information at deployment level. The term is therefore removed (but retained for deployments). Part of suggested changes in #133.
> Remove project-level bait use

- camtrap-dp-profile.json
This is a free text field that is likely difficult to separate from project description, so it is removed and users can describe it there. Extensive methodology is better discussed in a (data) paper. Part of suggested changes in #133.
> Remove methods

- camtrap-dp-profile.json
`"minItems": 1` is already part of data-package: https://specs.frictionlessdata.io/schemas/data-package.json
> Require at least one contributor, fix #138

- camtrap-dp-profile.json
@kbubnicki this wasn't something we discussed, but @yliefting and I think it would be a good idea to require this property at package level.
> Require data packages to have a creation date

- camtrap-dp-profile.json
Terms indicated as borrowed from Dublin Core (but with under_score writing for consistency). Part of suggested changes in #133.
> Add rights_holder and bibliographic_citation

- multimedia-table-schema.json
Fixes #123. Uses same pattern for url-or-path as in https://specs.frictionlessdata.io/schemas/data-resource.json
Will stop absolute and relative parent paths:
```
===  =====  ================  ================================================================================================================================================================================
row  field  code              message
===  =====  ================  ================================================================================================================================================================================
8      5  constraint-error  The cell "./file.jpg" in row at position "8" and field "file_path" at position "5" does not conform to a constraint: constraint "pattern" is …
```
> Use pattern for file path

- camtrap-dp-profile.json
One can only validate a Camtrap DP package properly, if it links to e.g.:
```
"profile": "https://raw.githubusercontent.com/tdwg/camtrap-dp/0.1.3/camtrap-dp-profile.json"
```
So it makes sense to make `profile` required. I think it also makes sense to require this to be a URI, but I don't think we can specify more, except maybe that it should contain `camtrap-dp`?
Note that not having a `profile` won't fail the validation, because `frictionless validate datapackage.json` will then assume it is a regular Data Package. Still, I think it is good to indicate to the user that we expect the `profile` property to be there.
> Make profile a required property, it needs to be a URL

- camtrap-dp-profile.json
Fix #147. Will validate that the keys in `vernacular_names` consist of 2 letters and have a string value (e.g. "en": "wolf").
> Express vernacular names as language_code: name pairs

- camtrap-dp-profile.json
Fix #145
Note that `resources` is already a required property in data package, so not repeated here.
Note that I did not add `uniqueItems` because validation will add numbers to resources if they have the same name (thus making them unique, and failing the enum).
> Require exactly 3 resources with names "deployments", "multimedia", "observations"

- observations-table-schema.json
Changes `observation_type = empty` to `observation_type = blank`.
Changes `observation_type = undefined` to `observation_type = unknown`:
- The term `undefined` has lead to some confusion with users, especially in combination with `unclassified`.
- `unknown` is more widely understood and used, e.g. at [Movebank](http://vocab.nerc.ac.uk/collection/MVB/current/MVB000023/). It was also suggested from the start: https://github.com/tdwg/camtrap-dp/issues/12#issuecomment-796741265
- For consistency, the value has also been renamed for sex and age.
> Use "unknown" rather than "undefined" (sex, age, observation_type) and "blank" rather than "empty"

- camtrap-dp-profile.json
- multimedia-table-schema.json
- observations-table-schema.json
PR to simplifying multimedia_access properties. Still in draft, since it hasn't been decided yet if the `public` property should be kept or not (`remote` and `auth` will disappear). See #124
> Remove multimedia access

- deployments-table-schema.json
Term is not required.
@tucotuco am I using wrong terms in this definition:
> Horizontal distance in meters from the given `latitude` and `longitude` describing the smallest circle containing the location of the camera trap. E.g. [111 meters](https://en.wikipedia.org/wiki/Decimal_degrees#Precision) for coordinates that were rounded to 3 decimals to conceal the precise location of an active camera. Term borrowed from [Darwin Core](http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters).
> Add and describe coordinate_uncertainty_in_meters

- camtrap-dp-profile.json
- deployments-table-schema.json
- multimedia-table-schema.json
- observations-table-schema.json
Relates to #172
Requires data resources to have a `schema` with a specific `name` (and therefore having a schema). That at least avoids Camtrap DP datasets without Table Schemas. Users could technically verbosely include their own schema (that will need one of the three names), but linking to the versioned one is easier. The setup generates readable error reports:
```
package-error The data package has an error: "'name' is a required property" at "resources/2/schema" in metadata and at "allOf/1/properties/resources/items/properties/schema/required" in profile
```
Notes:
I chose `name` rather than the already existing `title`, because title is intended for humans.
It didn't seem to work to make `schema` property itself required (those without one still passed validation), probably because …
> Require schema names (and therefore schemas)

- README.md
- index.md
Solves #151. @kbubnicki this is mainly a maintenance PR to better differentiate the repository from the website. The README is for the repository, and will mainly direct users to the website where usage guidelines are shown on the homepage.
> Split README in README (for repo) and index (for website)

- .github/workflows/validate-example-current-schema.yml
- .github/workflows/validate-example-versioned-schema.yml
- .github/workflows/validate-profile-and-schemas.yml
Update jobs titles as follows (rather than it being called `build` after the slash for both):
> Give more meaningful names to GitHub Actions jobs

- _layouts/profile.html
- camtrap-dp-profile.json
- example/datapackage.json
- pages/metadata.md
Implements https://github.com/tdwg/camtrap-dp/issues/189 by requiring a `scope = data` or `scope = media` property for licenses. Notes:
- `licenses` is not a required property (cf. Data Package and behaviour before), so it can be excluded. This is useful for e.g. exports from management systems where no license is specified.
- When added, at minimum **two** licenses are required, because we want people to always indicate one for data AND media. @ben-norton @kbubnicki **is that OK?** Note that one _could_ indicate even more licenses, e.g. if multiple licenses apply to the media files. It has the drawback that users don't know which one applies to which media files however, a drawback already discussed in #189.
- When added, the license needs a `scope` property, which should either be …
> Require license to have scope property

- camtrap-dp-profile.json
- example/datapackage.json
As suggested by @augusto-herrmann in https://github.com/tdwg/camtrap-dp/issues/189#issuecomment-1023193049, use the following terms in license scope:
```
data
linked media
```
The second was named `media`, which might be confusing that it is about the `media.csv` file rather than the media files referenced in `filePath` in `media.csv`. I opted for `linked media` (with space) in line with other vocab terms we have, such as `motion detection`.
Suggestions welcome.
> Update license scope definition

- camtrap-dp-profile.json
- deployments-table-schema.json
- media-table-schema.json
- observations-table-schema.json
Adds AC links discussed in #191 (2 pending). Also reverses interpretation of narrow/broad, which was incorrect before: see https://github.com/tdwg/camtrap-dp/issues/191#issuecomment-1028208259 regarding our previously incorrect interpretation of broad/narrowMatch. A broadMatch B means: A has a broader concept called B.
- **updated** `metadata:rightsHolder` has exact match http://ns.adobe.com/xap/1.0/rights/Owner which accepts literal values, while previous dc:rightsHolder does not
- **updated** `dep:deploymentID`, `media:deploymentID`, `obs:deploymentID` has a broader match http://rs.tdwg.org/dwc/terms/eventID, deploymentID is more specific
- **updated** `media:sequenceID`, `obs:sequenceID` has a broader match http://rs.tdwg.org/dwc/terms/eventID, sequenceID is more specific
- **new** …
> Add AC terms as skos: links + inverse narrow/broad

- _layouts/profile.html
- _layouts/tables.html
Makes sure each term on the website has a unique anchor, by prepending the table/property name with the term name (e.g. `#media.comments`). Fix #199
> Avoid duplicate anchors

- camtrap-dp-profile.json
We extend [Data Package](https://specs.frictionlessdata.io/schemas/data-package.json), which has little requirements for their resources (name + path/data).
We actually want the same requirements as [Tabular Data Package](https://specs.frictionlessdata.io/schemas/tabular-data-package.json) (but can't extend on that one), i.e. name + path/data + schema + profile. The first two are already borrowed from data-package, but we have to re-add schema + profile. Tabular data package also requires a specific value for profile, i.e. tabular-data-profile.
This PR implements that enforcement.
> Require *tabular* resources

- camtrap-dp-profile.json
Fix #228.
- As described in that issue, the 7 ranks are included after `taxonRank` but before `vernacularNames`.
- I kept the example at Canis lupus, which does not have a subfamily, so I left the example empty for `subfamily`.  @kbubnicki should I update to a scientific name that does have a subfamily?
- I added subfamily as an accepted rank for the scientific rank.
> Add higher classification in taxonomic coverage

- deployments-table-schema.json
- example/datapackage.json
- media-table-schema.json
- observations-table-schema.json
Validation otherwise fails with latest version of frictionless, since examples are arrays rather than strings
> Reduce examples to a single value to fix frictionless validation

- _layouts/profile.html
- _layouts/tables.html
- camtrap-dp-profile.json
- pages/data.md
Rather than 3 buttons on top, have side menu that sticks when scrolling, cf. the metadata page in #241. Since the width of the table is reduced, I moved the example below the constraints (rather than a separate column). Overall, I think the page is more readable and easier to navigate.
> Add table of content to data page

- example/datapackage.json
`https://www.checklistbank.org/dataset/3LR` is the better identifier to refer to the (always latest) version of CoL.
Ping @mdoering
> Change taxon ID reference to https://www.checklistbank.org/dataset/3LR

- _layouts/profile.html
- _layouts/tables.html
- camtrap-dp-profile.json
- deployments-table-schema.json
- example/datapackage.json
- media-table-schema.json
- observations-table-schema.json
- tests/helpers.py
- tests/validate_example_current_schema.py
- tests/validate_example_versioned_schema.py
- tests/validate_profile_and_schemas.py
Fix #272. This PR includes:
This will be required when we split `observations` and allow datasets to have either:
- `deployments`, `media`, `media-observations`
- `deployments`, `media`, `event-observations`
- `deployments`, `media`, `media-observations`, `event-observations`
Note: the resource `schema` is expected to be `https://raw.githubusercontent.com/tdwg/camtrap-dp/<version>/deployments-table-schema.json` with `<version>` e.g. `0.6`. That guarantees that the data is validated against the official Camtrap DP schema
The following conditions will result in validation error:
1. Resource has no `name`
1. Resource has no `path`, but `data`: this is new, it requires Camtrap DP tables to be files, not inline data
1. Resource has no `profile`
1. Resource has `profile`, but it is not …
> Allow more (custom) tables + update tests

- camtrap-dp-profile.json
- deployments-table-schema.json
Fix #290. Although the unit is always expressed in the definition (where applicable), I think it makes sense to indicate it as a separate property that can be picked up by software. So far we have 2 units. I indicated those as `unit: symbol_of_unit`:
- `m`: https://en.wikipedia.org/wiki/Metre
- `°`: https://en.wikipedia.org/wiki/Degree_(angle) (alternative `deg`)
> Add unit property

- pages/home.md
The [recorded webinar](https://www.gbif.org/event/f68927-b5c1-4ac8-a4ac-7d47645/exploring-camera-trap-data) is a good introduction to Camtrap DP and the intended adoption as a data publication format by GBIF.
I think it's worth mentioning it on the homepage and fits under implementations.
> Link to 2022 GBIF webinar on homepage

- _layouts/profile.html
- _layouts/tables.html
- deployments-table-schema.json
- event-observations-table-schema.json
- example/datapackage.json
- media-observations-table-schema.json
- media-table-schema.json
I removed the `name` property from the table schemas because it was no longer used by the validation and could be confused with the identical names of the resources using the schemas.
The IPT makes uses of that `name` property however and removing it caused issues (https://github.com/gbif/ipt/issues/1952#issuecomment-1444138714), so it's better to include it.
Note: it is fine that it is missing from version 0.6, since the schemas are copied for the IPT (and the `name` property was reintroduced manually in https://github.com/gbif/rs.gbif.org/commit/e3ef461b5d9ee8ccef681aebb8dd3c9d2b148c32).
Ping @mike-podolskiy90
> Reintroduce names for table schemas

- deployments-table-schema.json
- event-observations-table-schema.json
- media-observations-table-schema.json
- media-table-schema.json
I think it is fine to have it as a requirement that missing values MUST be expressed as empty strings in the CSVs. So not allowing `NaN`, `nan` or `NA`. CSV writers are very likely to meet that requirement.
> Only allow empty string for missing values

- media-table-schema.json
- Link fileMediaType to dc:format, closes #338. I used broadMatch, since dc:format can also describe physical media, while we only allow digital formats.
- Mention IANA in fileMediatype and add regular expression, closes #341.
- Link filePublic to ac:serviceExpectation, closes #339. I used broadMatch, since serviceExpectation allows physical media and does not impose a controlled value (or boolean).
> Update fileMediaType (and filePublic)

- camtrap-dp-profile.json
- deployments-table-schema.json
See #332. Note that these URLs don't resolve yet, but they are as listed on https://eco.tdwg.org/list/
> Use correct IRI for Humboldt terms

- example/datapackage.json
- observations-table-schema.json
Changes in response to #340, to make sure taxonID is a taxon identifier, not a name identifier. Closes #340.
> Update taxonID definition

- tests/httpserver.py
Two minor typo fixes:
```
./tests/httpserver.py:23: afterall ==> after all
./tests/httpserver.py:36: inifinite ==> infinite
```
> Typo fixes

- camtrap-dp-profile.json
- tests/requirements.txt
> Make compatible with latest frictionless-py

- CITATION.cff
- camtrap-dp-profile.json
- example/datapackage.json
- pages/example.md
The [differences](https://github.com/tdwg/camtrap-dp/compare/1.0...main) between this version and 1.0 are:
- Fix issue preventing validation with frictionless-py 5.17 and up (#383).
- Remove BOM character from example `observations.csv` (#370).
- Remove superfluous `spatial.bbox` from example `datapackage.json` (#370).
- Update some links in definitions (#368).
- Update README, homepage and add CITATION.cff (#382).
- Fix typos in test documentation (#372).
> Prepare version 1.0.1

- CITATION.cff
This allows to automatically set the keywords on Zenodo when a GitHub release triggers a deposit on Zenodo
> Add keywords to CITATION.cff

- camtrap-dp-profile.json
It is defined in https://specs.frictionlessdata.io/schemas/data-package.json, but by repeating it, resources* gets an asterisk in https://camtrap-dp.tdwg.org/metadata/#resources, making it clear that it is required.
> Repeat that "resources" is required

- example/datapackage.json
I think it makes more sense to refer to the camtrapdp R package than the more specialized camtraptor R package in the example dataset. The camtrapdp R package makes extensive use of this example dataset, and even has a function to load it: https://inbo.github.io/camtrapdp/reference/example_dataset.html
> Refer to camtrapdp software (rather than camtraptor) in example dataset

- pages/faq.md
This came up in a BIG_PICTURE meeting. We have a FAQ, but people might have more questions (that we could add). This PR adds a section at the bottom of the FAQ with a button to do so:
I'm adding it at the bottom, so they read/navigate through the existing answers first.
Rather than it linking to GitHub issues, I think it's better to use our underused discussion forum: https://github.com/tdwg/camtrap-dp/discussions
> Add a button at bottom of FAQ to ask question
